apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: "/var/lib/grafana"
        command: ["sh", "-c"]
        args:
        - >
          /bin/sh -c "grafana cli plugins install alexanderzobnin-zabbix-app && /run.sh"
      volumes:
      - name: grafana-data
        hostPath:
          path: "/home/anakin/Documentos/Server/Volumes/Grafana"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31000


