apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: init-permissions
        image: busybox:1.36.1
        command: ["sh", "-c"]
        args: ["chmod -R 777 /var/lib/grafana"]
        volumeMounts:
        - name: grafana-data
          mountPath: "/var/lib/grafana"
      containers:
      - name: grafana
        image: grafana/grafana:stable
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: "/var/lib/grafana"
        command: ["sh", "-c"]
        args:
        - >
          grafana-cli plugins install alexanderzobnin-zabbix-app && /run.sh
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30003