apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      initContainers:
        - name: install-hacs
          image: ubuntu:latest
          command:
            - "/bin/sh"
            - "-c"
            - "wget -q -O - https://install.hacs.xyz | sh -"
      containers:
        - name: homeassistant
          image: "ghcr.io/home-assistant/home-assistant:stable"
          ports:
            - containerPort: 8123  # Porta interna do Home Assistant
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: timezone-volume
              mountPath: /etc/localtime
              readOnly: true
            - name: dbus-volume
              mountPath: /run/dbus
              readOnly: true
          securityContext:
            privileged: true  # ⚠️ Use com cuidado
      volumes:
        - name: config-volume
          hostPath:
            path: /home/anakin/Documentos/Server/Volumes/Homeassistant/Config
        - name: timezone-volume
          hostPath:
            path: /home/anakin/Documentos/Server/Volumes/Homeassistant/localtime
        - name: dbus-volume
          hostPath:
            path: /home/anakin/Documentos/Server/Volumes/Homeassistant/dbus
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-nodeport
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30006
