apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      initContainers:  
      - name: install-hacs
        image: ubuntu:latest
        command:
          - "/bin/sh"
          - "-c"
          - "wget -q -O - https://install.hacs.xyz | sh -"
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:latest
        ports:
        - containerPort: 8123
        resources:
          requests:
            cpu: "500m"
            memory: "100Mi"
          limits:
            cpu: "1000m"
            memory: "800Mi"
        volumeMounts:
        - name: homeassistant-data
          mountPath: /var/lib/homeassistant
      volumes:
      - name: homeassistant-data
        persistentVolumeClaim:
          claimName: homeassistant-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
    nodePort: 31823
