apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
spec:
  replicas: 1  # Defina o número desejado de réplicas
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: WEBPASSWORD
          value: "Eunaoseiasenha22"  # Defina sua senha aqui
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "20Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 82
    targetPort: 80
    nodePort: 30004
