apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-secrets
type: Opaque
stringData:
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "sua_senha_secreta_e_forte" # MUDE ESTA SENHA PARA UMA FORTE E ÚNICA!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  labels:
    app: zabbix-db
spec:
  selector:
    matchLabels:
      app: zabbix-db
  template:
    metadata:
      labels:
        app: zabbix-db
    spec:
      containers:
      - name: zabbix-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-db-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: zabbix-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-db-pvc
  labels:
    app: zabbix-db
spec:
  accessModes:
    - ReadWriteOnce # Adapte se seu storage suporta ReadWriteMany
  resources:
    requests:
      storage: 20Gi # Ajuste o tamanho conforme sua necessidade de dados do Zabbix
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db-internal
  labels:
    app: zabbix-db
spec:
  selector:
    app: zabbix-db
  ports:
  - port: 5432
    targetPort: 5432
