apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30001
  selector:
    app: zabbix-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
      - name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:latest
        env:
        - name: ZBX_SERVER_HOST
          value: "zabbix-server"
        - name: DB_SERVER_HOST
          value: "zabbix-db-internal"
        - name: POSTGRES_USER
          value: "zabbix"
        - name: POSTGRES_PASSWORD
          value: "Zabbix"
#        resources:
#          requests:
#            memory: "256Mi"
#            cpu: "250m"
#          limits:
#            memory: "512Mi"
#            cpu: "500m"
